---
version: '3'

services:

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    command: start.sh jupyter lab --LabApp.token='*******************'  --LabApp.allow_remote_access='True' --LabApp.allow_origin='*'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      - skynet
    hostname: jupyter

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - skynet
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./self.crt:/etc/nginx/self.crt
      - ./self.key:/etc/nginx/self.key
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf

      
networks:
  skynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
